import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { Provider } from "@/components/Provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import Loading from "@/components/Loading";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={inter.className + " w-[95vw] md:px-[20vw] py-3"}>
          <Loading />
          <Navbar />
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
