version: '3'
services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./images:/app/images  # Map the local images folder to the container
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
    tty: true

volumes:
  images-volume:
